### ISSUE TITLE
OBJETO 3D CON A-FRAME Y AR.JS

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-equipo-josue#2]
[OBJETO-3D.pdf](https://github.com/SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-equipo-josue/files/6184462/OBJETO-3D.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
